apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-jmme
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-jmme
    app.kubernetes.io/part-of: integ-app-koro
  name: hacbs-test-project-jmme
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-jmme
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-jmme
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/integration1-ywyb-tenant/integ-app-koro/hacbs-test-project-jmme@sha256:4139f7f751bdc148502960fbcf1d9d3051c9b961b891a89c9fde3092f657f8b6
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
